### PR TITLE
Ammarzing branch

### PR DESCRIPTION
**Pull request by ammarhaider7**

### CODE REVIEW

**Comment by jessicabrentnall** [comment]
Love the work, so you mind if I edit your branch (change the lorem ipsum etc)

**Comment by jessicabrentnall** [comment]
Made a few changes, let me know what you think. What do you think of getting a sponsor logo on there as well? Thank you for being ammarzing

**Comment by ammarhaider7** [comment]
Updated with a blurred hero image of some code on a screen. Let me know if you think it's shite and ill revert

**Comment by jessicabrentnall** [comment]
I prefer the more plain background for now. I think it's because of the colours of the hero image. Maybe when we get some good images at the next event there might be something this works with

**Pull request merged**
